# Generated by Django 2.0.1 on 2018-03-28 13:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    replaces = [('application', '0001_squashed_0006_auto_20180326_1421'), ('application', '0002_auto_20180326_1755'), ('application', '0003_auto_20180326_1800'), ('application', '0004_auto_20180326_1813')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('additional_directions', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('data_credit', models.CharField(blank=True, max_length=100, null=True)),
                ('date_founded', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('residencies', models.NullBooleanField()),
                ('short_description', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
    ]
