# Generated by Django 2.0.1 on 2018-09-18 04:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    replaces = [('application', '0001_initial'), ('application', '0002_auto_20180328_2002'), ('application', '0003_space_validation_status'), ('application', '0004_space_business_model'), ('application', '0005_auto_20180330_1843'), ('application', '0006_auto_20180331_0027'), ('application', '0007_space_hours_of_operation'), ('application', '0008_auto_20180331_0205'), ('application', '0009_auto_20180331_0210'), ('application', '0010_auto_20180807_0133'), ('application', '0011_auto_20180807_0307'), ('application', '0012_auto_20180822_1619'), ('application', '0013_auto_20180824_1721')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('additional_directions', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('data_credit', models.CharField(blank=True, max_length=100, null=True)),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('residencies', models.NullBooleanField()),
                ('short_description', models.CharField(blank=True, max_length=140, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('membership', models.IntegerField(blank=True, null=True)),
                ('operational_status', models.CharField(blank=True, choices=[('In Operation', 'In Operation'), ('Planned', 'Planned'), ('Closed', 'Closed')], max_length=12, null=True)),
                ('size_in_sq_meters', models.IntegerField(blank=True, null=True)),
                ('users', models.IntegerField(blank=True, null=True)),
                ('wheelchair_accessibility', models.NullBooleanField()),
                ('validation_status', models.CharField(blank=True, choices=[('Verified', 'Verified Address and Operation Status'), ('Flagged', 'Flagged')], max_length=8, null=True)),
                ('business_model', models.CharField(blank=True, max_length=1000, null=True)),
                ('hours_of_operation', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceOption',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipOption',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='governance_type',
            field=models.ManyToManyField(blank=True, to='application.GovernanceOption'),
        ),
        migrations.AddField(
            model_name='space',
            name='ownership_type',
            field=models.ManyToManyField(blank=True, to='application.OwnershipOption'),
        ),
        migrations.CreateModel(
            name='AffiliationOption',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='network_affiliation',
            field=models.ManyToManyField(blank=True, to='application.AffiliationOption'),
        ),
    ]
