# Generated by Django 2.0.1 on 2018-03-04 19:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=20)),
                ('additional_directions', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=255)),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
