# Generated by Django 2.0.1 on 2018-03-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180328_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='validation_status',
            field=models.CharField(choices=[('VE', 'Verified'), ('FL', 'Flagged'), ('UK', 'Unknown Data Status')], default='UK', max_length=2),
        ),
    ]
