# Generated by Django 2.0.1 on 2018-03-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180305_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
