# Generated by Django 2.0.1 on 2018-03-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20180305_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='data_credit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='date_founded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='space',
            name='residencies',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='space',
            name='short_description',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
