# Generated by Django 2.0.1 on 2018-03-30 18:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_space_business_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='governance_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('COOP', 'Cooperative: members make decisions collectively'), ('DEM', 'Democratic: member-elected board makes decisions'), ('COM', 'Company: founders and/or hired staff make decisions'), ('SAT', 'Satellite: decisions are made by an external organization')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='ownership_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PRI', 'Private Sector: a for-profit business, corporation, or startup'), ('NON', 'Non-Profit: a registered non-profit organization'), ('EP', 'Educational: primary school'), ('ES', 'Educational: secondary school'), ('EU', 'Educational: university'), ('EV', 'Educational: vocational school'), ('GL', 'Government: Local or Municipal'), ('GP', 'Government: State or Provincial'), ('GN', 'Government: National'), ('UN', 'Unincorporated'), ('LIB', 'Library')], max_length=35, null=True),
        ),
    ]
