# Generated by Django 2.0.1 on 2018-03-20 21:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20180305_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='other_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
