# Generated by Django 2.0.1 on 2018-03-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20180331_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='hours_of_operation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
