# Generated by Django 2.0.1 on 2018-03-31 02:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_space_hours_of_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='governance_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cooperative', 'Cooperative: members make decisions collectively'), ('Democratic', 'Democratic: member-elected board makes decisions'), ('Company', 'Company: founders and/or hired staff make decisions'), ('Satellite', 'Satellite: decisions are made by an external organization')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='operational_status',
            field=models.CharField(blank=True, choices=[('In operation', 'In Operation'), ('Planned', 'Planned'), ('Closed', 'Closed')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='ownership_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Private Sector', 'Private Sector: a for-profit business, corporation, or startup'), ('Non-Profit', 'Non-Profit: a registered non-profit organization'), ('Primary Education', 'Educational: primary school'), ('Secondary Education', 'Educational: secondary school'), ('University', 'Educational: university'), ('Vocational', 'Educational: vocational school'), ('Local Government', 'Government: Local or Municipal'), ('Provincial Government', 'Government: Provincial'), ('National Government', 'Government: National'), ('Unincorporated', 'Unincorporated'), ('Library', 'Library')], max_length=167, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='validation_status',
            field=models.CharField(blank=True, choices=[('Verified', 'Verified Address and Operation Status'), ('Flagged', 'Flagged')], max_length=2, null=True),
        ),
    ]
