# Generated by Django 2.0.1 on 2018-08-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20180331_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='governance_type',
        ),
        migrations.RemoveField(
            model_name='space',
            name='ownership_type',
        ),
        migrations.AlterField(
            model_name='space',
            name='operational_status',
            field=models.CharField(blank=True, choices=[('In Operation', 'In Operation'), ('Planned', 'Planned'), ('Closed', 'Closed')], max_length=12, null=True),
        ),
    ]
