# Generated by Django 2.0.1 on 2018-08-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20180807_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceOption',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipOption',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='governance_type',
            field=models.ManyToManyField(blank=True, null=True, to='application.GovernanceOption'),
        ),
        migrations.AddField(
            model_name='space',
            name='ownership_type',
            field=models.ManyToManyField(blank=True, null=True, to='application.OwnershipOption'),
        ),
    ]
