# Generated by Django 2.0.1 on 2018-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20180807_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='governance_type',
            field=models.ManyToManyField(blank=True, to='application.GovernanceOption'),
        ),
        migrations.AlterField(
            model_name='space',
            name='ownership_type',
            field=models.ManyToManyField(blank=True, to='application.OwnershipOption'),
        ),
    ]
